kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: multicloud-operators-application
subjects:
- kind: ServiceAccount
  name: multicloud-operators-application
roleRef:
  kind: Role
  name: multicloud-operators-application
  apiGroup: rbac.authorization.k8s.io
